# Generated by Django 4.1.5 on 2023-01-17 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='uid',
            new_name='id',
        ),
    ]
