# Generated by Django 4.1.5 on 2023-01-17 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_uid_folder_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='id',
            new_name='uid',
        ),
    ]
